# Use postgres/example user/password credentials
version: '3.6'

services:
  places_db:
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: places_db
    volumes:
      - ./data:/var/lib/postgresql/data